name: Project Tests
on:
  push:
    branches:
      - testing
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.11
        uses: actions/checkout@v2
        with:
          python-version: "3.10.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r source/requirements.txt
      - name: Test with unittest
        run: python -m unittest test/test.py